$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  toolchains:
    or:
      - "javascript"

fileGroups:
  sources:
    - "src/**/*"
  tests:
    - "tests/**/*"
  configs:
    - "package.json"
    - "tsconfig*.json"
    - "vite.config.*"
    - "next.config.*"
    - "nuxt.config.*"
    - "playwright.config.*"
    - "svelte.config.*"
    - "app.config.*"
    - "eslint.config.*"
    - "postcss.config.*"
